spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 899667163269-cm8tcnib344179eqadahed1qqe4ul2fu.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email