spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 899667163269-c4je02dkpvd8f2lfooakukito3dbi5um.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email