server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  servlet:
    multipart:
      max-file-size: 2MB
  datasource:
    url: jdbc:mysql://localhost:3307/fridgerescue?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: fridgerescue
    password: fridgerescue
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
      show_sql: true
  output:
    ansi:
      enabled: always

  data:
    redis:
      host: localhost
      port: 6380

  elasticsearch:
    uris: "http://localhost:9200"

logging:
  level:
    '[team.rescue]': DEBUG
