server:
  port: 5000
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  servlet:
    multipart:
      max-file-size: 2MB
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${rds.username}
    password: ${rds.password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100

  data:
    redis:
      host: localhost
      port: 6380

  elasticsearch:
    uris: ${es.uri}

cloud:
  aws:
    credentials:
      accessKey: ${aws.s3.key.access}
      secretKey: ${aws.s3.key.secret}
    s3:
      bucket: ${aws.s3.bucket}
    region:
      static: ${cloud.aws.region.static}
    stack:
      auto: false

logging:
  level:
    '[team.rescue]': INFO
