spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 899667163269-6sjvi3cq5c4al56h1oqkc9c1d5a84vtt.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email