spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 899667163269-9ftjkpajvbit98iitgsoj907oa3ibciu.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email